services:
    db:
        build:
            dockerfile: ./db/postgres.dockerfile
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - app-network
    app:
        build:
            dockerfile: ./app/app.dockerfile
            args:
                GITHUB_REPO_URL_WITH_CREDENTIALS: ${GITHUB_REPO_URL_WITH_CREDENTIALS}
        depends_on:
            - db
        networks:
            - app-network
        ports:
            - 8000:8000
networks:
    app-network:
